In [ ]:
# !git clone https://github.com/ShathaTm/LK-Hadith-Corpus/
# !pip install camel-tools chromadb

In [1]:
import torch
import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
from typing import Dict, Any
from chromadb import Documents, EmbeddingFunction, Embeddings
from chromadb.utils.embedding_functions import register_embedding_function

import pandas as pd
import numpy as np
import os
from camel_tools.utils.dediac import dediac_ar
from camel_tools.utils.normalize import normalize_alef_ar,normalize_teh_marbuta_ar,normalize_alef_maksura_ar
from tqdm import tqdm

In [46]:
access_token = "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"
device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
# Custom Embedding Function
@register_embedding_function
class MyEmbeddingFunction(EmbeddingFunction):

    def __init__(self, model_name: str):
        self.model_name = model_name
        self.model = SentenceTransformerEmbeddingFunction(
            model_name=model_name,
            device=device,
            normalize_embeddings=True,
            token=access_token,
            backend="onnx",
            model_kwargs={"file_name": "model_int8.onnx"}
        )

    def __call__(self, docs: Documents) -> Embeddings:
        return self.model(docs)

    @staticmethod
    def name() -> str:
        return "GATE-AraBert-v1"

    def get_config(self) -> Dict[str, Any]:
        return dict(model_name=self.model_name)

    @staticmethod
    def build_from_config(config: Dict[str, Any]) -> "EmbeddingFunction":
        return MyEmbeddingFunction(config['model_name'])
    
model = MyEmbeddingFunction('models/gate_arabert_onnx/')

In [47]:
# Create Client
client = chromadb.PersistentClient(path="Islam")

In [ ]:
quran_collection = client.get_or_create_collection(
    name='quran',
    embedding_function=model,
    metadata={"hnsw:space": "cosine"}
)

tafsir_collection = client.get_or_create_collection(
    name='tafsir',
    embedding_function=model,
    metadata={"hnsw:space": "cosine"}
)

hadith_collection = client.get_or_create_collection(
    name='hadith',
    embedding_function=model,
    metadata={"hnsw:space": "cosine"}
)

In [ ]:
# queries = ['اركان الاسلام']
# res = hadith_collection.query(query_texts=queries,n_results=2)

# print('ids')
# for val in res['ids'][0]:
#     print(val)
#     print('-'*20)
# print('Documents')
# for val in res['documents'][0]:
#     print(val)
#     print('-'*20)
# print('='*20)
# print('Distances')
# for val in res['distances'][0]:
#     print(val)
#     print('-'*20)

# for val in res['metadatas'][0]:
#     print(val)

In [ ]:
# res

# Hadith

In [ ]:
df = pd.read_parquet('hf://datasets/SHK4K/hadith/data/train-00000-of-00001.parquet')

cols = df.columns.values
cols[5] = 'grade'
df.columns = cols

df[df['book']=='muslim']

df = df.dropna(subset=['arabicnumber'])

indx = df.groupby('book')['section'].unique().index
vals = df.groupby('book')['section'].unique().values

sections_nums = []
for i,val in enumerate(vals):
    arr = np.arange(1,len(val)+1,1).tolist()
    sections_nums.append([indx[i],dict(zip(val,arr))])
    
def add_sections(row):
    book = row.book
    
    for sec,dic in sections_nums:
        if sec == book:
            row['section_num'] = dic[row.section]
    return row

df = df.apply(add_sections,axis=1)
df = df[~(df['book'] == 'muslim')]

In [ ]:
print(df['book'].unique().tolist())
print(df['bookname'].unique().tolist())

In [ ]:
def meta(row):
    return {
        'book':row.book,
        'book_full':row.bookname,
        'section': row.section,
        'section_number': row.section_num,
        'hadith_number': row.arabicnumber,
        'hadith_comment' : row.comments,
        'grade' : row.grade,
        'source' : row.linkmin
    }

In [ ]:
def embed_docs(text):
    text = dediac_ar(text)
    text = normalize_alef_ar(text)
    text = text.replace('\u200f','')
    text = text.replace('  ', '')
    return model([text])

In [ ]:
ids, docs, metas = [], [], []
for row in tqdm(df.itertuples(), total=len(df)):
    chaphad = f"{row.book.lower()}:{row.arabicnumber}"
    doc = row.text
    ids.append(chaphad)
    docs.append(doc)
    metas.append(meta(row))

# ponytail: embed one-by-one is fine if sentence-transformers (GPU batches internally)
# batching here only helps for non-ST models

In [ ]:
# torch.save(embeddings, 'hadith_embeddings.pt')

In [ ]:
embeddings = torch.load('tensors/hadith.pt').tolist()

In [ ]:
# test
# hadith_collection.update(
#         ids=ids[:3],
#         documents=docs[:3],
#         embeddings=embeddings[:3],
#         metadatas=metas[:3]
#     )

In [ ]:
for i in tqdm(range(0, len(ids), 1000)):
    hadith_collection.add(
        ids=ids[i:i+1000],
        documents=docs[i:i+1000],
        embeddings=embeddings[i:i+1000],
        metadatas=metas[i:i+1000]
    )

In [ ]:
df['book'].unique()

# Quran

In [ ]:
# !git clone https://github.com/XMMR12/Quraan_DB

In [ ]:
import sqlite3
import re

# 1. Connect to the database file
conn = sqlite3.connect("Quraan_DB/Quraan.db")

import pandas as pd

quran = pd.read_sql("SELECT * FROM 'ALL'",con=conn)

quran.head()

In [ ]:
quran['AYA'] = quran['AYA'].apply(lambda x: (re.sub(r'\([0-9]\)','',x)).strip())

In [ ]:
quran[quran['AYA'] == '']

In [ ]:
quran.loc[3187].SURA

In [ ]:
quran.loc[3188, 'AYA'] = 'إِنَّهُۥ مِن سُلَيْمَـٰنَ وَإِنَّهُۥ بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ٠'
quran.loc[3188, 'SURA'] = quran.loc[3187, 'SURA']

In [ ]:
quran[quran['AYA'] == '']

In [ ]:
from tqdm import tqdm

quran_ids,docs,embs,metadatas = [],[],[],[]

for row in tqdm(quran.itertuples(),total=len(quran)):
    surah_num = row.SURA_num
    surah = row.SURA
    aya_num = row.AYA_num
    aya = row.AYA
    
    sura_aya = str(surah_num) + ':' + str(aya_num)
    # emb = embed_docs(aya)
    
    docs.append(aya)
    
    metadata = {
        'surah':surah,
        'surah_number': surah_num,
        'ayah_number': aya_num        
    }
    
    quran_ids.append(sura_aya)
    # embs.append(emb)
    metadatas.append(metadata)

# embs = torch.tensor(embs)
# torch.save(embs, 'quran_embeddings.pt')

In [ ]:
embs = torch.load('quran_embeddings.pt',weights_only=False).numpy().tolist()
embs = [emb[0] for emb in embs]

In [ ]:
for i in tqdm(range(0, len(quran_ids), 1000)):
    quran_collection.upsert(
        ids=quran_ids[i:i+1000],
        documents=docs[i:i+1000],
        embeddings=embs[i:i+1000],
        metadatas=metadatas[i:i+1000]
    )

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# # zip Islam folder
# !zip -r Islam.zip quran_embeddings.pt hadith_embeddings.pt
# !cp -rf Islam.zip /content/drive/MyDrive/Islam.zip

# Tafsir

In [ ]:
tafsir_collection.query(query_texts=['الرحمن فاسأل به خبيرا'],n_results=(5))

In [ ]:
SURAH_NAMES_AR = {
    1:"الفاتحة",2:"البقرة",3:"آل عمران",4:"النساء",5:"المائدة",
    6:"الأنعام",7:"الأعراف",8:"الأنفال",9:"التوبة",10:"يونس",
    11:"هود",12:"يوسف",13:"الرعد",14:"إبراهيم",15:"الحجر",
    16:"النحل",17:"الإسراء",18:"الكهف",19:"مريم",20:"طه",
    21:"الأنبياء",22:"الحج",23:"المؤمنون",24:"النور",25:"الفرقان",
    26:"الشعراء",27:"النمل",28:"القصص",29:"العنكبوت",30:"الروم",
    31:"لقمان",32:"السجدة",33:"الأحزاب",34:"سبأ",35:"فاطر",
    36:"يس",37:"الصافات",38:"ص",39:"الزمر",40:"غافر",
    41:"فصلت",42:"الشورى",43:"الزخرف",44:"الدخان",45:"الجاثية",
    46:"الأحقاف",47:"محمد",48:"الفتح",49:"الحجرات",50:"ق",
    51:"الذاريات",52:"الطور",53:"النجم",54:"القمر",55:"الرحمن",
    56:"الواقعة",57:"الحديد",58:"المجادلة",59:"الحشر",60:"الممتحنة",
    61:"الصف",62:"الجمعة",63:"المنافقون",64:"التغابن",65:"الطلاق",
    66:"التحريم",67:"الملك",68:"القلم",69:"الحاقة",70:"المعارج",
    71:"نوح",72:"الجن",73:"المزمل",74:"المدثر",75:"القيامة",
    76:"الإنسان",77:"المرسلات",78:"النبأ",79:"النازعات",80:"عبس",
    81:"التكوير",82:"الانفطار",83:"المطففين",84:"الانشقاق",85:"البروج",
    86:"الطارق",87:"الأعلى",88:"الغاشية",89:"الفجر",90:"البلد",
    91:"الشمس",92:"الليل",93:"الضحى",94:"الشرح",95:"التين",
    96:"العلق",97:"القدر",98:"البينة",99:"الزلزلة",100:"العاديات",
    101:"القارعة",102:"التكاثر",103:"العصر",104:"الهمزة",105:"الفيل",
    106:"قريش",107:"الماعون",108:"الكوثر",109:"الكافرون",110:"النصر",
    111:"المسد",112:"الإخلاص",113:"الفلق",114:"الناس",
}

In [ ]:
from datasets import load_dataset
import datasets

ds = load_dataset('SHK4K/quran_tafsir')
df = ds['train'].to_pandas()
df.head()

In [ ]:
df['book'].unique()

In [ ]:
print(df[(df['book']=='saadi') & (df['sura']==25) & (df['aya']==59)].iloc[0].tafsir)

In [ ]:
df['surah_name'] = df['sura'].apply(lambda x: SURAH_NAMES_AR[x])

In [ ]:
len(df)

In [ ]:
def tafsir_meta(row):
    return {
        'surah':row.surah_name,
        'surah_number':row.sura,
        'ayah_number':row.aya,
        'tafsir_book':row.book,
    }

In [ ]:
def embed_docs(text):
    text = dediac_ar(text)
    text = normalize_alef_ar(text)
    text = text.replace('\u200f','')
    text = text.replace('  ', '')
    return model([text])

In [ ]:
from tqdm import tqdm

tafsir_ids,docs,embs,metadatas = [],[],[],[]

for row in tqdm(df.itertuples(),total=len(df)):
    tafsir = row.tafsir
    surah_num = row.sura
    aya_num = row.aya
    book = row.book


    sura_aya = str(book)+':'+str(surah_num) + ':' + str(aya_num)

    docs.append(tafsir)

    metadata = tafsir_meta(row)

    tafsir_ids.append(sura_aya)
    metadatas.append(metadata)


# embs = [embed_docs(d) for d in tqdm(docs)]

In [ ]:
tafsir_embeddings = torch.load('tensors/tafsir_embeddings.pt').tolist()

In [ ]:
for i in tqdm(range(0, len(tafsir_ids), 1000)):
    tafsir_collection.upsert(
        ids=tafsir_ids[i:i+1000],
        documents=docs[i:i+1000],
        embeddings=tafsir_embeddings[i:i+1000],
        metadatas=metadatas[i:i+1000]
    )

# Books

In [30]:
from datasets import load_dataset

ds = load_dataset('SHK4K/islam_books', revision="4351759221be11acfea17148d04501192e7b25e1")
df = ds['train'].to_pandas()
df.head()

,_group,book_id,headers_tuple,book_category,book_type,book_date,book_name,category_name,all_authors,pages,page_count,chunks,chunk_page,__index_level_0__
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[23, 24]",2,# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,"23, 24",0
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,25,1
2,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,* و# من زعم أن الإيمان قول بلا عمل \n؛ فهو مرج...,25,1
3,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,<page>25</page>,25,1
4,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[26, 27]",2,* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,"26, 27",2

In [32]:
aqeedah = df[df['book_category']==1]

In [34]:
books = aqeedah.drop_duplicates(subset=['book_name'])
books = books[['book_id','book_category','book_name','all_authors']]
for row in books.itertuples():
    print(f'| {row.book_id} | {row.book_category} | {row.book_name} | {row.all_authors} |')

| 121 | 1 | إجماع السلف في الاعتقاد كما حكاه حرب الكرماني | حرب الكرماني |
| 170 | 1 | الجواب الصحيح لمن بدل دين المسيح لابن تيمية | ابن تيمية |
| 264 | 1 | تحقيق الإيمان لابن تيمية | ابن تيمية |
| 301 | 1 | تحقيق الاحتجاج بالقدر لابن تيمية | ابن تيمية |
| 323 | 1 | السنة لعبد الله بن أحمد | عبد الله بن أحمد |
| 792 | 1 | القصيدة التائية في القدر | ابن تيمية |
| 892 | 1 | رأس الحسين | ابن تيمية |
| 927 | 1 | منهاج السنة النبوية | ابن تيمية |
| 2864 | 1 | بيان تلبيس الجهمية في تأسيس بدعهم الكلامية | ابن تيمية |
| 2908 | 1 | الرد على من قال بفناء الجنة والنار | ابن تيمية |
| 6418 | 1 | أصول السنة لأحمد بن حنبل | أحمد بن حنبل |
| 6820 | 1 | الاستقامة | ابن تيمية |
| 6919 | 1 | زيارة القبور والاستنجاد بالمقبور | ابن تيمية |
| 7344 | 1 | الصارم المسلول على شاتم الرسول | ابن تيمية |
| 7564 | 1 | الإيمان لابن تيمية | ابن تيمية |
| 7609 | 1 | الحسنة والسيئة | ابن تيمية |
| 7623 | 1 | الرد على الجهمية والزنادقة للإمام أحمد ت صبري | أحمد بن حنبل |
| 7626 | 1 | الرد على المنطقيين | ابن تيمية |
| 7631 | 1 | الرسالة الأكملية في ما يجب لله من صفات الكمال | ابن تيمية |
| 7635 | 1 | الرسالة المدنية في تحقيق المجاز والحقيقة في صفات الله (مطبوع ضمن الفتوى الحموية الكبرى) | ابن تيمية |
| 8601 | 1 | شرح السنة للبربهاري | أبو محمد البربهاري |
| 8983 | 1 | الواسطة بين الحق والخلق | ابن تيمية |
| 9277 | 1 | الإخنائية أو الرد على الإخنائي ت العنزي | ابن تيمية |
| 10784 | 1 | الرسالة العرشية | ابن تيمية |
| 11071 | 1 | بغية المرتاد في الرد على المتفلسفة والقرامطة والباطنية | ابن تيمية |
| 11162 | 1 | حقوق آل البيت | ابن تيمية |
| 11216 | 1 | رسالة في أصول الدين | ابن تيمية |
| 11248 | 1 | شرح العقيدة الأصفهانية | ابن تيمية |
| 11258 | 1 | شرح حديث النزول | ابن تيمية |
| 11285 | 1 | قاعدة جامعة في توحيد الله وإخلاص الوجه والعمل له عبادة واستعانة | ابن تيمية |
| 11318 | 1 | التوحيد لابن عبد الوهاب | محمد بن عبد الوهاب |
| 11375 | 1 | نونية ابن القيم الكافية الشافية - ط مكتبة ابن تيمية | ابن القيم |
| 11620 | 1 | اقتضاء الصراط المستقيم لمخالفة أصحاب الجحيم | ابن تيمية |
| 11817 | 1 | النبوات لابن تيمية | ابن تيمية |
| 12769 | 1 | قاعدة عظيمة في الفرق بين عبادات أهل الإسلام والإيمان وعبادات أهل الشرك والنفاق | ابن تيمية |
| 18089 | 1 | الرد على الجهمية للدارمي - ت الشوامي | عثمان بن سعيد الدارمي |
| 18091 | 1 | نقض الدارمي على المريسي - ت الشوامي | عثمان بن سعيد الدارمي |
| 18098 | 1 | العقيدة الواسطية - ت ابن مانع | ابن تيمية |
| 18381 | 1 | الفتوى الحموية الكبرى | ابن تيمية |
| 20587 | 1 | الإيمان الأوسط - ط ابن الجوزي | ابن تيمية |
| 20879 | 1 | الجامع لعلوم الإمام أحمد - العقيدة | أحمد بن حنبل |
| 21499 | 1 | الفرقان بين أولياء الرحمن وأولياء الشيطان | ابن تيمية |
| 21506 | 1 | درء تعارض العقل والنقل | ابن تيمية |
| 21512 | 1 | مختصر منهاج السنة | ابن تيمية |
| 21565 | 1 | جواب في الحلف بغير الله والصلاة إلى القبور، ويليه: فصل في الاستغاثة | ابن تيمية |
| 22647 | 1 | العبودية | ابن تيمية |
| 22649 | 1 | قاعدة جليلة في التوسل والوسيلة | ابن تيمية |
| 22651 | 1 | مسألة في الكنائس | ابن تيمية |
| 22665 | 1 | العقيدة الواسطية - ت أشرف عبد المقصود | ابن تيمية |
| 22666 | 1 | التدمرية | ابن تيمية |
| 22667 | 1 | تحقيق القول في مسألة: عيسى كلمة الله والقرآن كلام الله | ابن تيمية |
| 22668 | 1 | مسألة فيما إذا كان في العبد محبة لما هو خير وحق ومحمود في نفسه | ابن تيمية |
| 22874 | 1 | الصفدية | ابن تيمية |
| 37816 | 1 | الإخنائية أو الرد على الإخنائي ت زهوي | ابن تيمية |
| 147670 | 1 | مسألة في توحيد الفلاسفة | ابن تيمية |

In [35]:
for book in aqeedah['book_id'].unique():
    chunks_num = np.arange(1,len(aqeedah[aqeedah['book_id']==book])+1)
    aqeedah.loc[aqeedah['book_id']==book,'chunk_num'] = chunks_num

In [36]:
def book_meta(row):
    return {
        'book_id': int(row.book_id),
        'book_name':row.book_name,
        'category_name': row.category_name,
        'all_authors': row.all_authors,
        'chunk_page': row.chunk_page,
        'book_pages': int(row.page_count),
        'source': f"https://shamela.ws/book/{row.book_id}/{row.chunk_page.split(', ')[0]}"
    }

In [48]:
def embed_docs(text):
    text = dediac_ar(text)
    text = normalize_alef_ar(text)
    text = text.replace('\u200f','')
    text = text.replace('  ', '')
    return model([text])

In [37]:
from tqdm import tqdm

aqeedah_ids,docs,metadatas = [],[],[]

for row in tqdm(aqeedah.itertuples(),total=len(aqeedah)):

    ids = str(row.book_category)+':'+str(row.book_id)+':'+str(int(row.chunk_num))

    docs.append(row.chunks)

    metadata = book_meta(row)

    aqeedah_ids.append(ids)
    metadatas.append(metadata)


# embs = [embed_docs(d) for d in tqdm(docs)]

100%|██████████| 31503/31503 [00:01<00:00, 30925.01it/s]

In [39]:
aqeedah[aqeedah['chunks'].str.contains('ثم الاختلاف كله (٨) قد يكون في التنزيل والحروف، كما في حديث ابن مسعود (٩) وقد يكون في التاويل كما يحتمله حديث عبد الله بن عمرو، فان حديث عمرو بن شعيب (١٠) يدل على ذلك،')]

/tmp/ipykernel_259667/3003248956.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  aqeedah[aqeedah['chunks'].str.contains('ثم الاختلاف كله (٨) قد يكون في التنزيل والحروف، كما في حديث ابن مسعود (٩) وقد يكون في التاويل كما يحتمله حديث عبد الله بن عمرو، فان حديث عمرو بن شعيب (١٠) يدل على ذلك،')]

Empty DataFrame
Columns: [_group, book_id, headers_tuple, book_category, book_type, book_date, book_name, category_name, all_authors, pages, page_count, chunks, chunk_page, __index_level_0__, chunk_num]
Index: []

In [41]:
for metadata in metadatas:
    if metadata['source']=='https://shamela.ws/book/11620/147':
        print(metadata)

{'book_id': 11620, 'book_name': 'اقتضاء الصراط المستقيم لمخالفة أصحاب الجحيم', 'category_name': 'العقيدة', 'all_authors': 'ابن تيمية', 'chunk_page': '147, 148', 'book_pages': 24, 'source': 'https://shamela.ws/book/11620/147'}

In [43]:
embs = torch.load('tensors/aqeedah_emb.pt').tolist()

In [20]:
client.delete_collection('aqeedah')

In [48]:
aqeedah_collection = client.get_or_create_collection(
    name='aqeedah',
    embedding_function=model,
    metadata={"hnsw:space": "cosine"}
)

In [52]:
len(aqeedah_collection.get()['ids'])

31503

In [22]:
for i in tqdm(range(0, len(aqeedah_ids), 1000)):
    aqeedah_collection.upsert(
        ids=aqeedah_ids[i:i+1000],
        documents=docs[i:i+1000],
        embeddings=embs[i:i+1000],
        metadatas=metadatas[i:i+1000]
    )

  0%|          | 0/32 [00:00<?, ?it/s]

100%|██████████| 32/32 [02:35<00:00,  4.86s/it]

In [23]:
aqeedah_collection.query(query_texts=['الاجماع على ان الله في السماء'],where={"book_id":121})

{'ids': [['1:121:43',
   '1:121:76',
   '1:121:55',
   '1:121:202',
   '1:121:67',
   '1:121:24',
   '1:121:45',
   '1:121:131',
   '1:121:200',
   '1:121:206']],
 'embeddings': None,
 'documents': [['[العليا] (¬١) السابعة، وعرش الرحمن [﷿] (¬٢) فوق الماء، والله ﵎ (¬٣) على العرش.\r* و# الكرسي موضع قدميه  \n(¬٤).\r* وهو يعلم ما في السموات [السبع وما في] (¬٥) الأرضين السبع، وما بينهن (¬٦)، [وما تحتهن] (¬٧)، وما تحت الثرى، وما في قعر البحار، ومَنْبَتَ كلِّ شعرة، [وكل] (¬٨) شجرة، وكل زرع، وكل نبت (¬٩)، ومسقط كل ورقة، وعدد ذلك كله (¬١٠)، وعدد الحصى، والرمل (¬١١)، والتراب، ومثاقيل الجبال، [وقطر الأمطار] (¬١٢)، وأعمال العباد، وآثارهم، وكلامهم، وأنفاسهم، و [تمتمتهم، <page>45</page>',
   '* و# السموات والأرضون (¬١) يوم القيامة في كفه  \n[وقبضته] (¬٢).\r',
   '* ولله [﷿] (¬٩) عرش، و# للعرش حَمَلَةٌ يحملونه \n.\r',
   'الله على العرش ودونه حجب <page>58</page>\nالرد على من احتج بمتشابه القرآن في مسألة العلو <page>59</page>',
   '* و# قلوب العباد بين [أصبعين من] (¬٦) أصابع الرحمن \n، يقلبها كيف يشاء، ويوعيها ما أراد.\r',
   'بل ذلك [كله] (¬١) بقضاء من الله وقدر (¬٢)، و [كل] (¬٣) ذلك بمشيئته في خلقه، وتدبيره [فيهم] (¬٤)، وما جرى في (¬٥) سابق علمه لهم (¬٦)، وهو العدل الحق [الذي] (¬٧) يفعل ما يريد.\r* ومن أقر بالعلم لزمه الإقرار بالقدر والمشيئة على الصِّغر والقَماءة (¬٨)، [والله الضار النافع، المضل الهادي، فتبارك الله أحسن الخالقين] (¬٩).\r* ولا نشهد على أحد من أهل القبلة أنه في النار لذنب عمله، و [لا] (¬١٠) لكبيرة أتى بها (¬١١) (¬١٢)، إلا أن يكون في ذلك حديث، [فيُروى الحديث] (¬١٣) <page>34</page>',
   '* وهو على العرش فوق السماء السابعة، ودونه حجب من نار ونور (¬٣) وظلمة (¬٤)، وما هو أعلم بها (¬٥)، فإن احتج مبتدع [أو] (¬٦) مخالف [أو زنديق (¬٧) بقول الله ﵎ (¬٨) اسمه: ﴿وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ﴾ (¬٩) [وبقوله] (¬١٠). ',
   'للأئمة (¬١). ',
   'خلق السموات والأرض <page>55</page>\nالكرسي موضع قدميه <page>56</page>',
   'قلوب العباد بين إصبعين من أصابع الرحمن <page>64</page>']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'book_pages': 1,
    'book_id': 121,
    'category_name': 'العقيدة',
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني',
    'chunk_page': '45',
    'source': 'https://shamela.ws/book/121/45',
    'all_authors': 'حرب الكرماني'},
   {'book_id': 121,
    'source': 'https://shamela.ws/book/121/52',
    'chunk_page': '52, 53',
    'book_pages': 1,
    'all_authors': 'حرب الكرماني',
    'category_name': 'العقيدة',
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني'},
   {'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني',
    'source': 'https://shamela.ws/book/121/46',
    'category_name': 'العقيدة',
    'book_pages': 2,
    'book_id': 121,
    'chunk_page': '46, 47',
    'all_authors': 'حرب الكرماني'},
   {'source': 'https://shamela.ws/book/121/58',
    'book_pages': 2,
    'book_id': 121,
    'category_name': 'العقيدة',
    'all_authors': 'حرب الكرماني',
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني',
    'chunk_page': '58, 59'},
   {'all_authors': 'حرب الكرماني',
    'source': 'https://shamela.ws/book/121/50',
    'category_name': 'العقيدة',
    'book_pages': 2,
    'chunk_page': '50, 51',
    'book_id': 121,
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني'},
   {'book_pages': 1,
    'category_name': 'العقيدة',
    'source': 'https://shamela.ws/book/121/34',
    'chunk_page': '34',
    'book_id': 121,
    'all_authors': 'حرب الكرماني',
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني'},
   {'book_id': 121,
    'chunk_page': '45, 46',
    'book_pages': 1,
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني',
    'category_name': 'العقيدة',
    'source': 'https://shamela.ws/book/121/45',
    'all_authors': 'حرب الكرماني'},
   {'chunk_page': '73, 74',
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني',
    'book_id': 121,
    'source': 'https://shamela.ws/book/121/73',
    'book_pages': 1,
    'category_name': 'العقيدة',
    'all_authors': 'حرب الكرماني'},
   {'book_id': 121,
    'category_name': 'العقيدة',
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني',
    'chunk_page': '55, 56',
    'book_pages': 2,
    'all_authors': 'حرب الكرماني',
    'source': 'https://shamela.ws/book/121/55'},
   {'book_pages': 1,
    'category_name': 'العقيدة',
    'book_id': 121,
    'all_authors': 'حرب الكرماني',
    'source': 'https://shamela.ws/book/121/64',
    'chunk_page': '64',
    'book_name': 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني'}]],
 'distances': [[0.5333555936813354,
   0.6189216375350952,
   0.6311037540435791,
   0.6458618640899658,
   0.6539565920829773,
   0.6569666862487793,
   0.6572883725166321,
   0.6632272005081177,
   0.6693814992904663,
   0.6735752820968628]]}

In [16]:
aqeedah['book_id'].unique()

array([   121,    170,    264,    301,    323,    792,    892,    927,
         2864,   2908,   6418,   6820,   6919,   7344,   7564,   7609,
         7623,   7626,   7631,   7635,   8601,   8983,   9277,  10784,
        11071,  11162,  11216,  11248,  11258,  11285,  11318,  11375,
        11620,  11817,  12769,  18089,  18091,  18098,  18381,  20587,
        20879,  21499,  21506,  21512,  21565,  22647,  22649,  22651,
        22665,  22666,  22667,  22668,  22874,  37816, 147670],
      dtype=uint32)