In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('data/shameladb_books.csv')
df = df[df['is_downloaded']]
df = df.dropna(subset=['content'])
df.head()

,book_id,book_name,book_category,book_type,book_date,authors,main_author,printed,group_id,hidden,...,book_up,category_name,main_author_name,main_author_death,all_authors,coauthors,is_downloaded,content,page_count,headers
114,121,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,1,1,280,1198,1198,1,NaN,0,...,NaN,العقيدة,حرب الكرماني,280,حرب الكرماني,NaN,True,"[{""page_id"": ""121-1"", ""body"": """", ""header"": """"...",225,"[""تقديم فضيلة الشيخ الدكتور/ محمد بن هادي المد..."
160,170,الجواب الصحيح لمن بدل دين المسيح لابن تيمية,1,1,728,54,54,1,NaN,0,...,NaN,العقيدة,ابن تيمية,728,ابن تيمية,NaN,True,"[{""page_id"": ""170-1"", ""body"": ""<span data-type...",3059,"[""مقدمة الكتاب"", ""فصل: دين الأنبياء واحد هو ال..."
168,178,اتباع السنن واجتناب البدع,1,1,643,603,603,1,NaN,0,...,NaN,العقيدة,ضياء الدين المقدسي,643,ضياء الدين المقدسي,NaN,True,"[{""page_id"": ""178-1"", ""body"": ""<span data-type...",69,"[""بسم الله الرحمن الرحيم وبه نستعين"", ""جزء من ..."
174,184,الصواعق المرسلة على الجهمية والمعطلة - ط عطاءا...,2,1,751,14,14,1,7345.0,0,...,NaN,الفرق والردود,ابن القيم,751,ابن القيم,NaN,True,"[{""page_id"": ""184-1"", ""body"": ""آثار الإمام ابن...",1654,"[""مقدمة المحقق"", ""التعريف بكتاب «الصواعق المرس..."
195,205,شفاء العليل في مسائل القضاء والقدر والحكمة وال...,1,1,751,14,14,1,NaN,0,...,NaN,العقيدة,ابن القيم,751,ابن القيم,NaN,True,"[{""page_id"": ""205-1"", ""body"": """", ""header"": """"...",1617,"[""مقدمة التحقيق"", ""توثيق نسبة الكتاب"", ""عنوان ..."

In [4]:
df = df[['book_id','book_category','book_type','book_date','book_name','category_name','all_authors','main_author_death','content','page_count']]

In [5]:
df = df[df['all_authors']!='تقي الدين السبكي']

# Sunnah

In [ ]:
sunnah = df[df['book_category'].isin([6,10,26,7,23,9,11])]
sunnah.head()

,book_id,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,content,page_count
611,642,9,1,279,كتاب العلل الواقع بآخر جامع الترمذي - ت بشار,العلل والسؤلات الحديثية,الترمذي,279,"[{""page_id"": ""642-1"", ""body"": ""<span data-type...",82
767,805,6,1,311,الحث على التجارة - من «الجامع» للخلال - ت العوضي,كتب السنة,أبو بكر الخلال,311,"[{""page_id"": ""805-1"", ""body"": """", ""header"": """"...",77
984,1077,6,1,311,السنة لأبي بكر بن الخلال,كتب السنة,أبو بكر الخلال,311,"[{""page_id"": ""1077-1"", ""body"": ""<span data-typ...",2004
1209,1362,6,1,256,بر الوالدين - البخاري - ت مكي,كتب السنة,البخاري,256,"[{""page_id"": ""1362-1"", ""body"": """", ""header"": ""...",351
1471,1733,6,1,360,المعجم الكبير للطبراني,كتب السنة,الطبراني,360,"[{""page_id"": ""1733-1"", ""body"": ""<span data-typ...",31863

In [84]:
sunnah = pd.concat([sunnah,firaq[firaq['book_id']==6105]])
sunnah = pd.concat([sunnah,firaq[(firaq['all_authors'].isin(['أحمد بن حنبل','ابن منده محمد بن إسحاق','عبد الله بن أحمد','ضياء الدين المقدسي','أبو محمد البربهاري','ابن بطة','عبد الحميد بن باديس','ابن أبي زمنين','عبد العزيز الملتاني']))&~(firaq['book_id'].isin([7623,178]))]])

In [85]:
len(sunnah)

116

In [86]:
sunnah.to_parquet('data/sunnah.parquet')

In [61]:
df_ = df[~df['book_category'].isin([6,10,26,7,23,9,17])]

In [45]:
list(zip(df_['book_category'].unique().tolist(),df_['category_name'].unique().tolist()))

[(1, 'العقيدة'), (2, 'الفرق والردود'), (11, 'أصول الفقه'), (3, 'التفسير')]

# Firaq

In [62]:
firaq = df[df['book_category']==1]
firaq.head()

,book_id,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,content,page_count
114,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[{""page_id"": ""121-1"", ""body"": """", ""header"": """"...",225
160,170,1,1,728,الجواب الصحيح لمن بدل دين المسيح لابن تيمية,العقيدة,ابن تيمية,728,"[{""page_id"": ""170-1"", ""body"": ""<span data-type...",3059
168,178,1,1,643,اتباع السنن واجتناب البدع,العقيدة,ضياء الدين المقدسي,643,"[{""page_id"": ""178-1"", ""body"": ""<span data-type...",69
195,205,1,1,751,شفاء العليل في مسائل القضاء والقدر والحكمة وال...,العقيدة,ابن القيم,751,"[{""page_id"": ""205-1"", ""body"": """", ""header"": """"...",1617
224,239,1,1,1206,ثلاثة الأصول وشروط الصلاة والقواعد الأربع,العقيدة,محمد بن عبد الوهاب,1206,"[{""page_id"": ""239-1"", ""body"": ""ثلاثة الأصول وأ...",61

In [64]:
firaq['all_authors'].unique().tolist()

['حرب الكرماني',
 'ابن تيمية',
 'ضياء الدين المقدسي',
 'ابن القيم',
 'محمد بن عبد الوهاب',
 'ابن باز',
 'عبد الله بن أحمد',
 'أبو الفضل التميمي',
 'أحمد بن حنبل',
 'شمس الدين الذهبي',
 'ابن قدامة',
 'سليمان بن سحمان',
 'ابن رجب الحنبلي',
 'عبد الله أبا بطين',
 'عبد الرحمن السعدي',
 'ابن بطة',
 'ابن أبي العز',
 'عبد الله بن محمد بن عبد الوهاب',
 'أبو محمد البربهاري',
 'عبد الحميد بن باديس',
 'ابن أبي زمنين',
 'ابن منده محمد بن إسحاق',
 'عثمان بن سعيد الدارمي',
 'عبد العزيز الملتاني',
 'مبارك الميلي',
 'ابن أبي زيد القيرواني']

In [49]:
list(zip(firaq['book_id'].unique().tolist(),firaq['book_name'].unique().tolist()))

[(121, 'إجماع السلف في الاعتقاد كما حكاه حرب الكرماني'),
 (170, 'الجواب الصحيح لمن بدل دين المسيح لابن تيمية'),
 (178, 'اتباع السنن واجتناب البدع'),
 (205, 'شفاء العليل في مسائل القضاء والقدر والحكمة والتعليل - ط عطاءات العلم'),
 (239, 'ثلاثة الأصول وشروط الصلاة والقواعد الأربع'),
 (264, 'تحقيق الإيمان لابن تيمية'),
 (301, 'تحقيق الاحتجاج بالقدر لابن تيمية'),
 (311, 'العقيدة الصحيحة وما يضادها ونواقض الإسلام'),
 (323, 'السنة لعبد الله بن أحمد'),
 (350, 'أصول الدين الإسلامي مع قواعده الأربع'),
 (390, 'الروح - ابن القيم - ط عطاءات العلم'),
 (572, 'إقامة البراهين على حكم من استغاث بغير الله أو صدق الكهنة والعرافين'),
 (583, 'كشف الشبهات - ت القاسم'),
 (792, 'القصيدة التائية في القدر'),
 (892, 'رأس الحسين'),
 (927, 'منهاج السنة النبوية'),
 (1049,
  'العقيدة التي حكاها أبو الفضل التميمي عن الإمام أحمد - المطبوع بآخر طبقات الحنابلة'),
 (1395, 'أصول الإيمان لمحمد بن عبد الوهاب - ت الجوابرة'),
 (2864, 'بيان تلبيس الجهمية في تأسيس بدعهم الكلامية'),
 (2908, 'الرد على من قال بفناء الجنة والنار'),
 (6394, 'فتاوى مهمة لعموم الأمة'),
 (6404, 'اختصاص القرآن بعوده إلى الرحيم الرحمن'),
 (6418, 'أصول السنة لأحمد بن حنبل'),
 (6462, 'الروح - ابن القيم - ط العلمية'),
 (6463, 'العلو للعلي الغفار'),
 (6467, 'تحريم النظر في كتب الكلام'),
 (6488, 'تميز الصدق من المين في محاورة الرجلين'),
 (6490, 'كلمة الإخلاص وتحقيق معناها - ط المكتب الإسلامي'),
 (6504, 'كشف الأوهام والإلتباس عن تشبيه بعض الأغبياء من الناس'),
 (6515, 'فتييان تتعلقان بتكفير الجهمية'),
 (6531, 'المنتقى من منهاج الاعتدال'),
 (6820, 'الاستقامة'),
 (6919, 'زيارة القبور والاستنجاد بالمقبور'),
 (7318, 'مختصر العلو للعلي العظيم'),
 (7344, 'الصارم المسلول على شاتم الرسول'),
 (7350, 'العرش للذهبي'),
 (7485,
  'أحاديث في الفتن والحوادث (مطبوع ضمن مؤلفات الشيخ محمد بن عبد الوهاب، الجزء الحادي عشر)'),
 (7486, 'أحاديث في الفتن والحوادث ط القاسم'),
 (7504, 'أصول الإيمان لمحمد بن عبد الوهاب - ضمن مجموع مؤلفاته'),
 (7516, 'إقامة الحجة والدليل وإيضاح المحجة والسبيل'),
 (7554, 'الانتصار لحزب الله الموحدين والرد على المجادل عن المشركين'),
 (7564, 'الإيمان لابن تيمية'),
 (7568, 'البيان المبدي لشناعة القول المجدي'),
 (7603, 'الجواهر المضية لمجدد الدعوة النجدية'),
 (7609, 'الحسنة والسيئة'),
 (7614, 'الدرة البهية شرح القصيدة التائية في حل المشكلة القدرية'),
 (7620, 'الرد على البردة'),
 (7623, 'الرد على الجهمية والزنادقة للإمام أحمد ت صبري'),
 (7626, 'الرد على المنطقيين'),
 (7629,
  'الرسائل الشخصية (مطبوع ضمن مؤلفات الشيخ محمد بن عبد الوهاب، الجزء السادس)'),
 (7631, 'الرسالة الأكملية في ما يجب لله من صفات الكمال'),
 (7635,
  'الرسالة المدنية في تحقيق المجاز والحقيقة في صفات الله (مطبوع ضمن الفتوى الحموية الكبرى)'),
 (7637, 'الرسالة المفيدة'),
 (7664, 'الضياء الشارق في رد شبهات الماذق المارق'),
 (8137, 'مسائل الجاهلية'),
 (8206, 'الإبانة الكبرى - ابن بطة'),
 (8352, 'شرح العقيدة الطحاوية - ط الرسالة'),
 (8524,
  'القواعد الأربع (مطبوع ضمن مؤلفات الشيخ محمد بن عبد الوهاب، الجزء الأول)'),
 (8529, 'القول السديد شرح كتاب التوحيد ط النفائس'),
 (8532, 'الكلمات النافعة في المكفرات الواقعة'),
 (8589, 'التوضيح والبيان لشجرة الإيمان'),
 (8599, 'رسالة في حكم السحر والكهانة مع بعض الفتاوى المهمة'),
 (8601, 'شرح السنة للبربهاري'),
 (8820, 'العقيدة الصحيحة وما يضادها'),
 (8983, 'الواسطة بين الحق والخلق'),
 (9092, 'العقائد الإسلامية لابن باديس'),
 (9277, 'الإخنائية أو الرد على الإخنائي ت العنزي'),
 (9430,
  'التنبيهات اللطيفة على ما احتوت عليه العقيدة الواسطية من المباحث المنيفة'),
 (9677, 'منهج أهل السنة والجماعة في السمع والطاعة'),
 (9698, 'أصول السنة لابن أبي زمنين'),
 (10090, 'تفسير أسماء الله الحسنى للسعدي'),
 (10165, 'حكم الإسلام فيمن زعم أن القرآن متناقض'),
 (10321, 'التمسك بالسنن والتحذير من البدع'),
 (10458, 'القول السديد شرح كتاب التوحيد ط الوزارة'),
 (10549, 'شرح العقيدة الطحاوية - ط المكتب الإسلامي التاسعة'),
 (10777, 'شرح العقيدة الطحاوية - ط الأوقاف السعودية - بتعليقات أحمد شاكر'),
 (10784, 'الرسالة العرشية'),
 (11071, 'بغية المرتاد في الرد على المتفلسفة والقرامطة والباطنية'),
 (11079, 'تأسيس التقديس في كشف تلبيس داود بن جرجيس'),
 (11123, 'تنبيه ذوي الألباب السليمة عن والوقوع في الألفاظ المبتدعة الوخيمة'),
 (11126,
  'ثلاثة الأصول (مطبوع ضمن مؤلفات الشيخ محمد بن عبد الوهاب، الجزء الأول)'),
 (11146,
  'جواب أهل السنة النبوية في نقض كلام الشيعة والزيدية (مطبوع ضمن الرسائل والمسائل النجدية، الجزء الرابع، القسم الأول)'),
 (11162, 'حقوق آل البيت'),
 (11179, 'أصول الإيمان لابن باز'),
 (11181, 'دحض شبهات على التوحيد من سوء الفهم لثلاثة أحاديث'),
 (11216, 'رسالة في أصول الدين'),
 (11218, 'رسالة في القرآن وكلام الله'),
 (11221,
  'فضل الإسلام (مطبوع ضمن مؤلفات الشيخ محمد بن عبد الوهاب، الجزءالأول)'),
 (11248, 'شرح العقيدة الأصفهانية'),
 (11255, 'شرح ثلاثة الأصول لابن باز'),
 (11258, 'شرح حديث النزول'),
 (11285, 'قاعدة جامعة في توحيد الله وإخلاص الوجه والعمل له عبادة واستعانة'),
 (11318, 'التوحيد لابن عبد الوهاب'),
 (11329, 'فائدة جليلة في قواعد الأسماء الحسنى'),
 (11352, 'كشف الشبهتين'),
 (11353, 'كشف غياهب الظلام عن أوهام جلاء الأوهام'),
 (11375, 'نونية ابن القيم الكافية الشافية - ط مكتبة ابن تيمية'),
 (11381,
  'مجموعة رسائل في التوحيد والإيمان (مطبوع ضمن مؤلفات الشيخ محمد بن عبد الوهاب، الجزء الأول)'),
 (11620, 'اقتضاء الصراط المستقيم لمخالفة أصحاب الجحيم'),
 (11817, 'النبوات لابن تيمية'),
 (12021, 'شفاء العليل في مسائل القضاء والقدر والحكمة والتعليل - ط المعرفة'),
 (12078,
  'مفيد المستفيد في كفر تارك التوحيد (مطبوع ضمن مؤلفات الشيخ محمد بن عبد الوهاب، الجزء الأول)'),
 (12091, 'منهاج أهل الحق والاتباع في مخالفة أهل الجهل والابتداع'),
 (12769,
  'قاعدة عظيمة في الفرق بين عبادات أهل الإسلام والإيمان وعبادات أهل الشرك والنفاق'),
 (13022, 'الرد على الجهمية لابن منده - ط المكتبة الأثرية'),
 (16422, 'نونية ابن القيم الكافية الشافية - ط عطاءات العلم'),
 (17816, 'السيف المسلول على من سب الرسول'),
 (18089, 'الرد على الجهمية للدارمي - ت الشوامي'),
 (18091, 'نقض الدارمي على المريسي - ت الشوامي'),
 (18098, 'العقيدة الواسطية - ت ابن مانع'),
 (18381, 'الفتوى الحموية الكبرى'),
 (20587, 'الإيمان الأوسط - ط ابن الجوزي'),
 (20879, 'الجامع لعلوم الإمام أحمد - العقيدة'),
 (21499, 'الفرقان بين أولياء الرحمن وأولياء الشيطان'),
 (21506, 'درء تعارض العقل والنقل'),
 (21512, 'مختصر منهاج السنة'),
 (21565,
  'جواب في الحلف بغير الله والصلاة إلى القبور، ويليه: فصل في الاستغاثة'),
 (22647, 'العبودية'),
 (22649, 'قاعدة جليلة في التوسل والوسيلة'),
 (22651, 'مسألة في الكنائس'),
 (22665, 'العقيدة الواسطية - ت أشرف عبد المقصود'),
 (22666, 'التدمرية'),
 (22667, 'تحقيق القول في مسألة: عيسى كلمة الله والقرآن كلام الله'),
 (22668, 'مسألة فيما إذا كان في العبد محبة لما هو خير وحق ومحمود في نفسه'),
 (22874, 'الصفدية'),
 (30822,
  'بيان التوحيد الذي بعث الله به الرسل جميعا وبعث به خاتمهم محمدا عليه السلام'),
 (30850, 'كشف الشبهات - ط الأوقاف السعودية'),
 (30855, 'لمعة الاعتقاد'),
 (30869, 'نواقض الإسلام'),
 (30870, 'وجوب تحكيم شرع الله ونبذ ما خالفه'),
 (30882, 'معنى لا إله إلا الله - محمد بن عبد الوهاب'),
 (30917, 'التحذير من البدع'),
 (36080, 'الناهية عن طعن أمير المؤمنين معاوية'),
 (36949, 'المقدمة الزهرا في إيضاح الإمامة الكبرى'),
 (37348, 'رسالة الشرك ومظاهره'),
 (37816, 'الإخنائية أو الرد على الإخنائي ت زهوي'),
 (97806, 'عقيدة السلف - مقدمة أبي زيد القيرواني لكتابه الرسالة'),
 (147670, 'مسألة في توحيد الفلاسفة'),
 (151130, 'مقدمة تشتمل على أن جميع الرسل كان دينهم الإسلام'),
 (151141, 'كلمة الإخلاص وتحقيق معناها - ضمن رسائل ابن رجب')]

In [89]:
raw_text = df[~df['book_id'].isin(sunnah['book_id'].unique().tolist())]
raw_text

,book_id,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,content,page_count
114,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[{""page_id"": ""121-1"", ""body"": """", ""header"": """"...",225
160,170,1,1,728,الجواب الصحيح لمن بدل دين المسيح لابن تيمية,العقيدة,ابن تيمية,728,"[{""page_id"": ""170-1"", ""body"": ""<span data-type...",3059
168,178,1,1,643,اتباع السنن واجتناب البدع,العقيدة,ضياء الدين المقدسي,643,"[{""page_id"": ""178-1"", ""body"": ""<span data-type...",69
174,184,2,1,751,الصواعق المرسلة على الجهمية والمعطلة - ط عطاءا...,الفرق والردود,ابن القيم,751,"[{""page_id"": ""184-1"", ""body"": ""آثار الإمام ابن...",1654
195,205,1,1,751,شفاء العليل في مسائل القضاء والقدر والحكمة وال...,العقيدة,ابن القيم,751,"[{""page_id"": ""205-1"", ""body"": """", ""header"": """"...",1617
...,...,...,...,...,...,...,...,...,...,...
7714,37816,1,1,728,الإخنائية أو الرد على الإخنائي ت زهوي,العقيدة,ابن تيمية,728,"[{""page_id"": ""37816-1"", ""body"": ""<span data-ty...",295
8106,97806,1,1,386,عقيدة السلف - مقدمة أبي زيد القيرواني لكتابه ا...,العقيدة,ابن أبي زيد القيرواني,386,"[{""page_id"": ""97806-1"", ""body"": ""عقيدة السلف\r...",76
8427,147670,1,1,728,مسألة في توحيد الفلاسفة,العقيدة,ابن تيمية,728,"[{""page_id"": ""147670-1"", ""body"": ""مَسْألةٌ فِي...",104
8542,151130,1,1,795,مقدمة تشتمل على أن جميع الرسل كان دينهم الإسلام,العقيدة,ابن رجب الحنبلي,795,"[{'page_id': '151130-1', 'body': 'مقدمة تشتمل ...",17
8552,151141,1,1,795,كلمة الإخلاص وتحقيق معناها - ضمن رسائل ابن رجب,العقيدة,ابن رجب الحنبلي,795,"[{""page_id"": ""151141-1"", ""body"": ""التوحيد أو ت...",60

In [91]:
len(raw_text),len(sunnah),len(df), len(raw_text)+len(sunnah)

(143, 116, 259, 259)

In [ ]:
raw_text = pd.concat([raw_text,df[df['book_id'].isin([6655,36080,9697,117359])]])

In [ ]:
raw_text.to_parquet('data/raw_text.parquet')