In [62]:
import pandas as pd
import sqlite3
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import display, Markdown

In [22]:
conn = sqlite3.connect("../data/ar-tafsir-al-tabari.db")

     name
0  tafsir

In [23]:
df = pd.read_sql_query("SELECT * from tafsir;", conn)
df.head()

,ayah_key,group_ayah_key,from_ayah,to_ayah,ayah_keys,text
0,1:1,1:1,1:1,1:1,1:1,<div class=ar lang=ar><p>القول في تأويل <span ...
1,1:2,1:2,1:2,1:2,1:2,<div class=ar lang=ar><p>القول في تأويل فاتحة ...
2,1:3,1:3,1:3,1:3,1:3,<div class=ar lang=ar><p>القول في تأويل قوله: ...
3,1:4,1:4,1:4,1:4,1:4,<div class=ar lang=ar><p>القول في تأويل قوله: ...
4,1:5,1:5,1:5,1:5,1:5,<div class=ar lang=ar><p>القول في تأويل قوله ج...

In [ ]:
sns.set(style="whitegrid")

In [25]:
df.columns

Index(['ayah_key', 'group_ayah_key', 'from_ayah', 'to_ayah', 'ayah_keys',
       'text'],
      dtype='str')

In [66]:
display(Markdown(df[df['group_ayah_key']=='2:51']['text'].values[0]))

<div class=ar lang=ar><p>القول في تأويل قوله تعالى <span class="qpc-hafs">﴿وَإِذْ وَاعَدْنَا﴾</span></p><p>اختلفت القَرَأَة في قراءة ذلك، [[في المطبوعة في الموضعين: "القراء"، كما فعل كثيرا فيما مضى. والقَرَأَة جمع قارئ.]] فقرأ بعضهم: <span class="qpc-hafs">﴿واعدنا﴾</span> بمعنى أن الله تعالى واعد موسى موافاة الطور لمناجاته، [[في المطبوعة: "ملاقاة الطور"، ولا أدري لم غيره من غيره! .]] فكانت المواعدة من الله لموسى، ومن موسى لربه. وكان من حجتهم على اختيارهم قراءة <span class="qpc-hafs">﴿واعدنا﴾</span> على"وعدنا" أن قالوا: كل اتعاد كان بين اثنين للالتقاء والاجتماع، [[في المطبوعة: "كل إبعاد. . أو الاجتماع"، ولا أدري لم فعل ذلك! . واتعد اتعادا افتعل، من الوعد.]] فكل واحد منهما مواعد صاحبه ذلك. فلذلك -زعموا- [[في المطبوعة: "فلذلك رموا أنه وجب" بزيادة أنه"، وهي زيادة مفسدة للمعنى.]] وجب أن يُقضى لقراءة من قرأ <span class="qpc-hafs">﴿واعدنا﴾</span> بالاختيار على قراءة من قرأ"وعدنا".</p><p>وقرأ بعضهم:"وعدنا" بمعنى أن الله الواعد والمنفرد بالوعد دونه. وكان من حجتهم في اختيارهم ذلك أن قالوا: إنما تكون المواعدة بين البشر، فأما الله جل ثناؤه، فإنه المنفرد بالوعد والوعيد في كل خير وشر. قالوا: وبذلك جاء التنزيل في القرآن كله، فقال جل ثناؤه: <span class="qpc-hafs">﴿إِنَّ اللَّهَ وَعَدَكُمْ وَعْدَ الْحَقِّ﴾</span> [إبراهيم: ٢٢] وقال: <span class="qpc-hafs">﴿وَإِذْ يَعِدُكُمُ اللَّهُ إِحْدَى الطَّائِفَتَيْنِ أَنَّهَا لَكُمْ﴾</span> [الأنفال: ٧] . قالوا: فكذلك الواجب أن يكون هو المنفرد بالوعد في قوله:"وإذ وعدنا موسى".</p><h3>* *</h3><p>والصواب عندنا في ذلك من القول: أنهما قراءتان قد جاءت بهما الأمة وقرأت بهما القَرَأَة، وليس في القراءة بإحداهما إبطال معنى الأخرى، وإن كان في إحداهما زيادة معنى على الأخرى من جهة الظاهر والتلاوة. [[انظر ما مضى في تفسير"الظاهر": ٤٤، والمراجع.]] فأما من جهة المفهوم بهما فهما متفقتان. وذلك أن من أخبر عن شخص أنه وعد غيره اللقاء بموضع من المواضع، فمعلوم أن الموعود ذلك واعد صاحبه من لقائه بذلك المكان، مثل الذي وعده من ذلك صاحبه، إذا كان وعده ما وعده إياه من ذلك عن اتفاق منهما عليه. ومعلوم أن موسى صلوات الله عليه لم يعده ربه الطور إلا عن رضا موسى بذلك، إذ كان موسى غير مشكوك فيه أنه كان بكل ما أمر الله به راضيا، وإلى محبته فيه مسارعا. ومعقول أن الله تعالى لم يعد موسى ذلك، إلا وموسى إليه مستجيب. وإذ كان ذلك كذلك، فمعلوم أن الله عز ذكره قد كان وعد موسى الطور، ووعده موسى اللقاء. فكان الله عز ذكره لموسى واعدا مواعدا له المناجاة على الطور، [[في المطبوعة: قد كان وعد موسى" بزيادة"قد"، وفيها أيضًا "وكان الله عز وجل لموسى واعد ومواعدا"، والواو هنا ليست بشيء في قوله"وكان"، و"مواعدا".]] وكان موسى واعدا لربه مواعدا له اللقاء. فبأي القراءتين من"وعد" و"واعد" قرأ القارئ، فهو للحق في ذلك -من جهة التأويل واللغة- مصيب، لما وصفنا من العلل قبل. [[في المطبوعة: "فهو الحق في ذلك. . . "، وهو خطأ.]]</p><p>ولا معنى لقول القائل: إنما تكون المواعدة بين البشر، وأن الله بالوعد والوعيد منفرد في كل خير وشر. وذلك أن انفراد الله بالوعد والوعيد في الثواب والعقاب، والخير والشر، والنفع والضر الذي هو بيده وإليه دون سائر خلقه -لا يحيل الكلام الجاري بين الناس في استعمالهم إياه عن وجوهه، ولا يغيره عن معانيه. والجاري بين الناس من الكلام المفهوم ما وصفنا: من أن كل اتعاد كان بين اثنين، [[في المطبوعة هنا أيضًا كما سلف: "كل إبعاد"، وهو فساد وخطأ.]] فهو وعد من كل واحد منهما صاحبه، ومواعدة بينهما، وأن كل واحد منهما واعد صاحبه مواعد، وأن الوعد الذي يكون به الانفراد من الواعد دون الموعود، إنما هو ما كان بمعنى"الوعد" الذي هو خلاف"الوعيد".</p><h3>* *</h3><p>القول في تأويل قوله تعالى <span class="qpc-hafs">﴿مُوسَى﴾</span></p><p>وموسى -فيما بلغنا- بالقبطية كلمتان، يعني بهما: ماء وشجر."فمو"، هو الماء، و"شا" هو الشجر. [[في المطبوعة والمخطوطة: "سا" وأثبت ما في التاريخ.]] وإنما سمي بذلك -فيما بلغنا- لأن أمه لما جعلته في التابوت -حين خافت عليه من فرعون وألقته في اليم، كما أوحى الله إليها، وقيل: إن اليم الذي ألقته فيه هو النيل - دفعته أمواج اليم حتى أدخلته بين أشجار عند بيت فرعون، فخرج جواري آسية امرأة فرعون يغتسلن، فوجدن التابوت فأخذنه، فسمي باسم المكان الذي أصيب فيه، كان ذلك بمكان فيه ماء وشجر، [[في المطبوعة: "وكان ذلك المكان فيه" وليست بشيء.]] فقيل: موسى، ماء وشجر. كذلك:-</p><p>٩١٢ - حدثني موسى بن هارون قال، حدثنا عمرو بن حماد، عن أسباط بن نصر، عن السدي. [[الأثر: ٩١٢ تاريخ الطبري ١: ٢٠١ في خبر طويل.]]</p><h3>* *</h3><p>وقال أبو جعفر: وهو موسى بن عمران بن يصهر بن قاهث بن لاوي بن يعقوب إسرائيل الله بن إسحاق ذبيح الله ابن إبراهيم خليل الله، فيما زعم ابن إسحاق.</p><p>٩١٣ - حدثني بذلك ابن حميد قال، حدثنا سلمة بن الفضل، عنه. [[الأثر: ٩١٣ - مختصر من خبر نسبه في تاريخ الطبري ١: ١٩٨.]] .</p><h3>* *</h3><p>القول في تأويل قوله تعالى <span class="qpc-hafs">﴿أَرْبَعِينَ لَيْلَةً﴾</span></p><p>ومعنى ذلك: وإذ واعدنا موسى أربعين ليلة بتمامها. فالأربعون ليلة كلها داخلة في الميعاد.</p><p>وقد زعم بعض نحويي البصرة أن معناه: وإذ واعدنا موسى انقضاء أربعين ليلة، أي رأس الأربعين، ومثل ذلك بقوله: <span class="qpc-hafs">﴿وَاسْأَلِ الْقَرْيَةَ﴾</span> [يوسف: ٨٢] وبقولهم:"اليوم أربعون منذ خرج فلان"،"واليوم يومان". أي اليوم تمام يومين، وتمام أربعين.</p><p>قال أبو جعفر: وذلك خلاف ما جاءت به الرواية عن أهل التأويل، وخلاف ظاهر التلاوة. فأما ظاهر التلاوة، فإن الله جل ثناؤه قد أخبر أنه واعد موسى أربعين ليلة، فليس لأحد إحالة ظاهر خبره إلى باطن، [[انظر تفسير"ظاهر" و" باطن" فيما سلف ص: ٤٤، والمراجع قبلها.]] بغير برهان دال على صحته.</p><h3>* *</h3><p>وأما أهل التأويل فإنهم قالوا في ذلك ما أنا ذاكره، وهو ما:-</p><p>٩١٤ - حدثني به المثنى بن إبراهيم قال، حدثنا آدم قال، حدثنا أبو جعفر، عن الربيع بن أنس، عن أبي العالية قوله: <span class="qpc-hafs">﴿وإذ واعدنا موسى أربعين ليلة﴾</span> ، قال: يعني ذا القعدة وعشرا من ذي الحجة. وذلك حين خلف موسى أصحابه واستخلف عليهم هارون، فمكث على الطور أربعين ليلة، وأنزل عليه التوراة في الألواح -وكانت الألواح من برد [[في المطبوعة: "وكانت الألواح من زبرجد"، والصواب ما أثبته من المخطوطة، ومما جاء عن أبي العالية، في صفة الألواح ٩: ٤٦ (بولاق) .]] - فقربه الرب إليه نجيا، وكلمه، وسمع صريف القلم. وبلغنا أنه لم يحدث حدثا في الأربعين ليلة حتى هبط من الطور. [[صريف الأقلام: صوتها وصريرها وهي تجري بما تكتبه الملائكة. وقوله: "لم يحدث حدثا"، أي لم يكربه ما يكرب الناس من قضاء الحاجة.]]</p><p>٩١٥ - وحدثت عن عمار بن الحسن، حدثنا عبد الله بن أبي جعفر، عن أبيه، عن الربيع، بنحوه.</p><p>٩١٦ - حدثنا ابن حميد قال، حدثنا سلمة بن الفضل، عن ابن إسحاق قال: وعد الله موسى-حين أهلك فرعون وقومه، ونجاه وقومه ثلاثين ليلة، ثم أتمها بعشر، فتم ميقات ربه أربعين ليلة، يلقاه ربه فيها ما شاء. [[في المطبوعة: "تلقاه ربه فيها بما شاء".]] واستخلف موسى هارون على بني إسرائيل، وقال: إني متعجل إلى ربي فاخلفني في قومي ولا تتبع سبيل المفسدين. فخرج موسى إلى ربه متعجلا للُقِيِّه شوقا إليه، [[في المطبوعة: "للقائه"، وهما سواء في المعنى.]] وأقام هارون في بني إسرائيل ومعه السامري يسير بهم على أثر موسى ليلحقهم به. [[الأثر: ٩١٦ - صدر هذا الأثر في تاريخ الطبري ١: ٢١٧ - ٢١٨، ولكن قطعه الطبري، وأتمه من خبر السدي.]]</p><p>٩١٧ - حدثني موسى بن هارون قال، حدثنا عمرو بن حماد قال، حدثنا أسباط عن السدي قال: انطلق موسى واستخلف هارون على بني إسرائيل، وواعدهم ثلاثين ليلة، وأتمها الله بعشر. [[الأثر: ٩١٧ - في تاريخ الطبري في خبر طويل ١: ٢١٨، وسيأتي تمامه في رقم: ٩١٩.]]</p><h3>* *</h3><p>القول في تأويل قوله تعالى <span class="qpc-hafs">﴿ثُمَّ اتَّخَذْتُمُ الْعِجْلَ مِنْ بَعْدِهِ وَأَنْتُمْ ظَالِمُونَ (٥١) ﴾</span></p><p>وتأويل قوله: <span class="qpc-hafs">﴿ثم اتخذتم العجل من بعده﴾</span> ، ثم اتخذتم في أيام مواعدة موسى العجل إلها، من بعد أن فارقكم موسى متوجها إلى الموعد. و"الهاء" في قوله"من بعده" عائدة على ذكر موسى.</p><p>فأخبر جل ثناؤه المخالفين نبينا ﷺ من يهود بني إسرائيل، المكذبين به المخاطبين بهذه الآية -عن فعل آبائهم وأسلافهم، وتكذيبهم رسلهم، وخلافهم أنبياءهم، مع تتابع نعمه عليهم، وشيوع آلائه لديهم، [[في المطبوعة: "سبوغ آلائه". وشيوع آلائه: ظهورها وعمومها حتى استوى فيها جميعهم. وانظر ما سيأتي بعد ص: ٧٧، تعليق: ٢.]] مُعَرِّفَهم بذلك أنهم -من خلاف محمد ﷺ وتكذيبهم به، وجحودهم لرسالته، مع علمهم بصدقه [[في المطبوعة: "من خلافهم محمدا. . ".]] - على مثل منهاج آبائهم وأسلافهم، ومحذِّرَهم من نزول سطوته بهم =بمقامهم على ذلك من تكذيبهم= ما نزل بأوائلهم المكذبين بالرسل: من المسخ واللعن وأنواع النقمات.</p><p>وكان سبب اتخاذهم العجل، ما:-</p><p>٩١٨ - حدثني به عبد الكريم بن الهيثم قال، حدثنا إبراهيم بن بشار الرمادي قال، حدثنا سفيان بن عيينة قال، حدثنا أبو سعيد، عن عكرمة، عن ابن عباس قال: لما هجم فرعون على البحر هو وأصحابه، وكان فرعون على فرس أدهم ذنوب حصان، فلما هجم على البحر، هاب الحصان أن يقتحم في البحر، فتمثل له جبريل على فرس أنثى وديق، فلما رآها الحصان تقحم خلفها. [[انظر آخر الأثر رقم: ٩٠٩ فهو هذا بنصه، ثم يأتي تمامه.]] قال: وعرف السامري جبريل، لأن أمه حين خافت أن يذبح خلفته في غار وأطبقت عليه، فكان جبريل يأتيه فيغذوه بأصابعه، فيجد في بعض أصابعه لبنا، وفي الأخرى عسلا وفي الأخرى سمنا، فلم يزل يغذوه حتى نشأ. فلما عاينه في البحر عرفه، فقبض قبضة من أثر فرسه. قال: أخذ من تحت الحافر قبضة. -قال سفيان: فكان ابن مسعود يقرؤها: " فقبضت قبضة من أثر فرس الرسول" [طه: ٩٦] .</p><p>قال أبو سعيد قال عكرمة، عن ابن عباس: وألقي في رَوْع السامري [[الروع (بضم الراء) : القلب والعقل. وقع ذلك في روعى: أي في نفسي وخلدي وبالي.]] إنك لا تلقيها على شيء فتقول:"كن كذا وكذا" إلا كان. فلم تزل القبضة معه في يده حتى جاوز البحر. فلما جاوز موسى وبنو إسرائيل البحر، وأغرق الله آل فرعون، قال موسى لأخيه هارون: اخلفني في قومي وأصلح. ومضى موسى لموعد ربه. قال: وكان مع بني إسرائيل حَلْي من حَلْي آل فرعون قد تعوَّروه، [[تعور الشيء واستعاره: أخذه عارية، كما تقول: تعجب واستعجب.]] فكأنهم تأثموا منه، فأخرجوه لتنزل النار فتأكله. فلما جمعوه، قال السامري بالقبضة التي كانت في يده هكذا، [[قال بالقبضة: رفعها مشيرا بيده ليلقيها. وقد مضى تفسير ذلك في ص: ٥٤ تعليق: ٣.]] فقذفها فيه - وأومأ ابن إسحاق بيده هكذا - وقال: كن عجلا جسدا له خوار. فصار عجلا جسدا له خوار، وكان تدخل الريح في دبره وتخرج من فيه، يسمع له صوت، فقال: هذا إلهكم وإله موسى. فعكفوا على العجل يعبدونه، فقال هارون: يا قوم إنما فتنتم به، وإن ربكم الرحمن فاتبعوني وأطيعوا أمري! قالوا: لن نبرح عليه عاكفين حتى يرجع إلينا موسى.</p><p>٩١٩ - حدثني موسى بن هارون قال، حدثنا عمرو بن حماد قال، حدثنا أسباط بن نصر، عن السدي: لما أمر الله موسى أن يخرج ببني إسرائيل - يعني من أرض مصر - أمر موسى بني إسرائيل أن يخرجوا، وأمرهم أن يستعيروا الحلي من القبط. فلما نجى الله موسى ومن معه من بني إسرائيل من البحر، وغرق آل فرعون، أتى جبريل إلى موسى يذهب به إلى الله. فأقبل على فرس، فرآه السامري فأنكره وقال: إنه فرس الحياة! فقال حين رآه: إن لهذا لشأنا. فأخذ من تربة الحافر -حافر الفرس- فانطلق موسى، واستخلف هارون على بني إسرائيل، وواعدهم ثلاثين ليلة، وأتمها الله بعشر. فقال لهم هارون: يا بني إسرائيل، إن الغنيمة لا تحل لكم، وإن حَلْي القبط إنما هو غنيمة، فاجمعوها جميعا، واحفروا لها حفرة فادفنوها، فإن جاء موسى فأحلها أخذتموها، وإلا كان شيئا لم تأكلوه. فجمعوا ذلك الحَلْي في تلك الحفرة، وجاء السامري بتلك القبضة فقذفها، فأخرج الله من الحلي عجلا جسدا له خوار. وعدت بنو إسرائيل موعد موسى، فعدوا الليلة يوما واليوم يوما، فلما كان تمام العشرين، خرج لهم العجل. فلما رأوه قال لهم السامري: هذا إلهكم وإله موسى فنسي - يقول: ترك موسى إلهه ههنا وذهب يطلبه. فعكفوا عليه يعبدونه، وكان يخور ويمشي. فقال لهم هارون: يا بني إسرائيل إنما فتنتم به -يقول: إنما ابتليتم به، يقول: بالعجل- وإن ربكم الرحمن. فأقام هارون ومن معه من بني إسرائيل لا يقاتلونهم، وانطلق موسى إلى إلهه يكلمه، فلما كلمه قال له: ما أعجلك عن قومك يا موسى؟ قال: هم أولاء على أثري وعجلت إليك رب لترضى. قال: فإنا قد فتنا قومك من بعدك وأضلهم السامري، فأخبره خبرهم. قال موسى؛ يا رب هذا السامري أمرهم أن يتخذوا العجل، أرأيت الروح من نفخها فيه؟ قال الرب: أنا. قال: رب أنت إذا أضللتهم. [[الأثر: ٩١٩ - مضى صدره في رقم: ٩١٧. وفي التاريخ ١: ٢١٨.]]</p><p>٩٢٠ - حدثنا ابن حميد قال، حدثنا سلمة عن ابن إسحاق قال: كان -فيما ذكر لي- أن موسى قال لبني إسرائيل فيما أمره الله عز وجل به: استعيروا منهم - يعني من آل فرعون - الأمتعة والحلي والثياب، فإني منفلكم أموالهم مع هلاكهم. فلما أذن فرعون في الناس، كان مما يحرض به على بني إسرائيل أن قال: حين ساروا لم يرضوا أن خرجوا بأنفسهم، حتى ذهبوا بأموالكم معهم! [[الأثر: ٩٢٠ - في تاريخ الطبري ١: ٢١٦. وفي المطبوعة"أن يخرجوا بأنفسهم"، وأثبت ما في المخطوطة والتاريخ. نفله الشيء: جعله نفلا، أي غنيمة مستباحة.]]</p><p>٩٢١ - حدثنا ابن حميد قال، حدثنا سلمة قال، حدثني محمد بن إسحاق، عن حكيم بن جبير، عن سعيد بن جبير، عن ابن عباس قال: كان السامري رجلا من أهل باجَرْما، وكان من قوم يعبدون البقر، وكان حب عبادة البقر في نفسه، وكان قد أظهر الإسلام في بني إسرائيل. فلما فضل هارون في بني إسرائيل، وفصل موسى إلى ربه، [[فصل فلان عن البلد يفصل فصولا: إذا خرج وفارقها]] قال لهم هارون: أنتم قد حُمِّلتم أوزارا من زينة القوم - آل فرعون - وأمتعة وحليا، فتطهروا منها، فإنها نجس. وأوقد لهم نارا فقال: اقذفوا ما كان معكم من ذلك فيها. قالوا: نعم.</p><p>فجعلوا يأتون بما كان فيهم من تلك الأمتعة وذلك الحلي، [[في المطبوعة: "بما كان معهم"، غيروه ليستقيم على دارج ما ألفوه.]] فيقذفون به فيها. حتى إذا تكسر الحلي فيها، ورأى السامري، أثر فرس جبريل، فأخذ ترابا من أثر حافره، [[في المطبوعة: "أخذ ترابا"، حذفوا الفاء ليستقي على عربيتهم، فيما زعموا.]] ثم أقبل إلى النار فقال لهارون: [[في تاريخ الطبري: "ثم أقبل إلى الحفرة. . . ".]] يا نبي الله، ألقي ما في يدي؟ قال: نعم. ولا يظن هارون إلا أنه كبعض ما جاء به غيره من ذلك الحلي والأمتعة، فقذفه فيها وقال:"كن عجلا جسدا له خوار"، فكان، للبلاء والفتنة. فقال: هذا إلهكم وإله موسى. فعكفوا عليه، وأحبوه حبا لم يحبوا مثله شيئا قط. يقول الله عز وجل: <span class="qpc-hafs">﴿فنسي﴾</span> [طه: ٨٨] أي ترك ما كان عليه من الإسلام - يعني السامري - (أَفَلا يَرَوْنَ أَلا يَرْجِعُ إِلَيْهِمْ قَوْلا وَلا يَمْلِكُ لَهُمْ ضَرًّا وَلا نَفْعًا) [طه: ٨٩] وكان اسم السامري موسى بن ظفر، وقع في أرض مصر، فدخل في بني إسرائيل. [[هو كما ذكر في أول الخبر من أهل"باجرما"، وباجرما: قرية من أعمال البليخ قرب الرقة، من أرض الجزيرة. (ياقوت) . ويقال: موضع قبل نصيبن (معجم ما استعجم) . وقال الميداني في شرح المثل: [خطب يسير في خطب كبير] أن الزباء كانت من أهل باجرما وتتكلم العربية.]] فلما رأى هارون ما وقعوا فيه قال: <span class="qpc-hafs">﴿يَا قَوْمِ إِنَّمَا فُتِنْتُمْ بِهِ وَإِنَّ رَبَّكُمُ الرَّحْمَنُ فَاتَّبِعُونِي وَأَطِيعُوا أَمْرِي قَالُوا لَنْ نَبْرَحَ عَلَيْهِ عَاكِفِينَ حَتَّى يَرْجِعَ إِلَيْنَا مُوسَى﴾</span> [طه: ٩٠-٩١] فأقام هارون فيمن معه من المسلمين ممن لم يفتتن، وأقام من يعبد العجل على عبادة العجل، وتخوف هارون، إن سار بمن معه من المسلمين، أن يقول له موسى: فرقت بين بني إسرائيل ولم ترقب قولي. وكان له هائبا مطيعا [[الأثر: ٩٢١ - في تاريخ الطبري ١: ٢١٩ - ٢٢٠.]] .</p><p>٩٢٢ - حدثني يونس بن عبد الأعلى قال، أخبرنا ابن وهب قال، قال ابن زيد: لما أنجى الله عز وجل بني إسرائيل من فرعون، وأغرق فرعون ومن معه، قال موسى لأخيه هارون: اخلفني في قومي وأصلح ولا تتبع سبيل المفسدين. قال: لما خرج موسى وأمر هارون بما أمره [[في المطبوعة: "بما أمره به".]] وخرج موسى متعجلا مسرورا إلى الله، قد عرف موسى أن المرء إذا أنجح في حاجة سيده، كان يسره أن يتعجل إليه [[في المطبوعة: "نجح"، وأنجح: أدرك طلبته وبلغ النجاح. وإن كنت أخشى أن يكون في الكلمة تصحيف خفي عليَّ.]] . قال: وكان حين خرجوا استعاروا حليا وثيابا من آل فرعون، فقال لهم هارون: إن هذه الثياب والحلي لا تحل لكم، فاجمعوا نارا، فألقوه فيها فأحرقوه. قال: فجمعوا نارا. قال: وكان السامري قد نظر إلى أثر دابة جبريل، وكان على فرس أنثى - وكان السامري في قوم موسى - قال: فنظر إلى أثره فقبض منه قبضة، فيبست عليها يده. فلما ألقى قوم موسى الحلي في النار، وألقى السامري معهم القبضة، صور الله جل وعز ذلك لهم عجلا ذهبا، فدخلته الريح، فكان له خوار، فقالوا: ما هذا؟ فقال: السامري الخبيث: <span class="qpc-hafs">﴿هَذَا إِلَهُكُمْ وَإِلَهُ مُوسَى فَنَسِيَ﴾</span> ، الآية، إلى قوله: <span class="qpc-hafs">﴿حَتَّى يَرْجِعَ إِلَيْنَا مُوسَى﴾</span> [طه: ٨٨-٩١] قال: حتى إذا أتى موسى الموعد، قال الله: <span class="qpc-hafs">﴿وَمَا أَعْجَلَكَ عَنْ قَوْمِكَ يَا مُوسَى قَالَ هُمْ أُولاءِ عَلَى أَثَرِي﴾</span> فقرأ حتى بلغ: <span class="qpc-hafs">﴿أَفَطَالَ عَلَيْكُمُ الْعَهْدُ﴾</span> [طه: ٨٦] .</p><p>٩٢٣ - حدثنا القاسم بن الحسن قال، حدثنا الحسين قال، حدثني حجاج، عن ابن جريج، عن مجاهد في قوله: <span class="qpc-hafs">﴿ثم اتخذتم العجل من بعده﴾</span> قال: العجل: حسيل البقرة [[الحسيل (بفتح فكسر) : ولد البقرة.]] . قال: حلي استعاروه من آل فرعون، فقال لهم هارون: أخرجوه فتطهروا منه وأحرقوه. وكان السامري قد أخذ قبضة من أثر فرس جبريل فطرحه فيه، فانسبك، فكان له كالجوف تهوي فيه الرياح.</p><p>٩٢٤ - حدثني المثنى بن إبراهيم قال، حدثنا آدم قال، حدثنا أبو جعفر، عن الربيع، عن أبي العالية، قال: إنما سمي العجل، لأنهم عجلوا فاتخذوه قبل أن يأتيهم موسى.</p><p>٩٢٥ - حدثني محمد بن عمرو الباهلي قال، حدثنا أبو عاصم قال، حدثني عيسى، عن ابن أبي نجيح، عن مجاهد بنحو حديث القاسم عن الحسن.</p><p>٩٢٦ - حدثني المثنى بن إبراهيم قال، حدثنا أبو حذيفة قال، حدثنا شبل، عن ابن أبي نجيح، عن مجاهد بنحوه [[الأثران: ٩٢٥، ٩٢٦ - في المخطوطة ساق إسناد الأثرين جميعا في موضع واحد قال: "قال حدثنا عيسى - وحدثني المثنى بن إبراهيم، قال، حدثنا أبو حذيفة قال، حدثنا شبل - جميعا عن أبي نجيح، عن مجاهد في قوله: "ثم اتخذتم العجل" قال: العجل: حسيل البقرة. . . " ثم ساق نص ما في الأثر: ٩٢٤. فآثرت ترك ما في المطبوعة على حاله.]]</p><h3>* *</h3><p>القول في تأويل قوله: <span class="qpc-hafs">﴿وَأَنْتُمْ ظَالِمُونَ (٥١) ﴾</span></p><p>يعني" وأنتم واضعو العبادة في غير موضعها، لأن العبادة لا تنبغي إلا لله عز وجل، وعبدتم أنتم العجل ظلما منكم، ووضعا للعبادة في غير موضعها. وقد دللنا -في غير هذا الموضع مما مضى من كتابنا- أن أصل كل ظلم، وضع الشيء في غير موضعه، فأغنى ذلك عن إعادته في هذا الموضع [[انظر ما مضى ١: ٥٢٣ - ٥٢٤.]] .</p><h3>* *</h3><p>القول في تأويل قوله تعالى ذكره <span class="qpc-hafs">﴿ثُمَّ عَفَوْنَا عَنْكُمْ مِنْ بَعْدِ ذَلِكَ لَعَلَّكُمْ تَشْكُرُونَ (٥٢) ﴾</span></p><p>قال أبو جعفر: وتأويل قوله: <span class="qpc-hafs">﴿ثم عفونا عنكم من بعد ذلك﴾</span> ، يقول: تركنا معاجلتكم بالعقوبة،"من بعد ذلك"، أي من بعد اتخاذكم العجل إلها. كما:-</p><p>٩٢٧ - حدثني به المثنى بن إبراهيم قال، حدثنا آدم العسقلاني قال، حدثنا أبو جعفر، عن الربيع، عن أبي العالية: <span class="qpc-hafs">﴿ثم عفونا عنكم من بعد ذلك﴾</span> ، يعني من بعد ما اتخذتم العجل.</p><h3>* *</h3><p>وأما تأويل قوله: <span class="qpc-hafs">﴿لعلكم تشكرون﴾</span> ، فإنه يعني به: لتشكروا. ومعنى"لعل" في هذا الموضع معنى"كي". وقد بينت فيما مضى قبلُ أن أحد معاني"لعل""كي"، بما فيه الكفاية عن إعادته في هذا الموضع [[انظر ما مضى ١: ٣٦٤ - ٣٦٥.]] .</p><h3>* *</h3><p>فمعنى الكلام إذا: ثم عفونا عنكم من بعد اتخاذكم العجل إلها، لتشكروني على عفوي عنكم، إذ كان العفو يوجب الشكر على أهل اللب والعقل.</p></div>

In [50]:
df[df['text']=='']

     ayah_key group_ayah_key from_ayah to_ayah ayah_keys text
58       2:52           2:51
106     2:100           2:99
113     2:107          2:106
145     2:139          2:138
186     2:180          2:179
...       ...            ...       ...     ...       ...  ...
6231    114:2          114:1
6232    114:3          114:1
6233    114:4          114:1
6234    114:5          114:1
6235    114:6          114:1

[2600 rows x 6 columns]

In [48]:
df.isna().sum()

ayah_key          0
group_ayah_key    0
from_ayah         0
to_ayah           0
ayah_keys         0
text              0
dtype: int64

In [ ]:
conn.close()